import { defineConfig } from 'tsup';

// Two-config build:
//   1. Library — src/index.ts → dist/{index.js, index.cjs, index.d.ts, index.d.cts}
//      Public-API surface that consumers `import` or `require`.
//   2. CLI — src/cli/index.ts → dist/cli/{index.js, index.cjs}
//      Bin entry used by `npx @vibeguard-dev/local <subcommand>`.
//      Banner prepends `#!/usr/bin/env node` so the file works as a
//      stand-alone executable on Unix; Windows uses the .cmd shim
//      generated by npm.
//
// Why two configs (instead of multi-entry single config)?
//   The CLI needs the shebang banner; the library must NOT have one
//   because bundlers in downstream consumer projects can choke on it.
//   tsup's `banner` option applies to all entries in the same config,
//   so we keep them separate. defineConfig([…]) processes the array
//   sequentially: lib first (with `clean: true` to wipe dist/), then
//   CLI (with `clean: false` so it doesn't wipe what the lib just wrote).

const baseConfig = {
  splitting: false,
  minify: false,
  target: 'es2022' as const,
  // libpg-query is a peer dependency — never bundle it. Consumers
  // install it alongside @vibeguard-dev/local.
  external: ['libpg-query'],
  // Server-side Node only for the initial release. Document this in
  // README; consider browser builds in 2.x if there's pull.
  platform: 'node' as const,
  // Shim `import.meta.url` (and `__dirname` / `__filename`) across
  // ESM and CJS outputs. Without this, tsup compiles
  // `createRequire(import.meta.url)` in src/parser.ts to
  // `createRequire(undefined)` in the CJS bundle, which makes
  // `require('libpg-query')` throw — so CJS consumers see a spurious
  // "peer dependency missing" error. Discovered via post-publish
  // smoke against the npm registry.
  shims: true,
};

export default defineConfig([
  // 1. Library
  {
    ...baseConfig,
    entry: ['src/index.ts'],
    format: ['esm', 'cjs'],
    dts: true,
    sourcemap: true,
    clean: true,
  },
  // 2. CLI — separate config so the shebang banner only lands here
  {
    ...baseConfig,
    entry: ['src/cli/index.ts'],
    outDir: 'dist/cli',
    format: ['esm', 'cjs'],
    dts: false, // CLI is invoked, not imported as a typed module
    sourcemap: false,
    clean: false, // lib config already wiped dist/
    banner: { js: '#!/usr/bin/env node' },
  },
]);
